### ISSUE TITLE
Error de ortografia en README.me

### ISSUE THREAD

**Issue by martinvilu** [martinvilu/pruebas#36]
@TomasSautu @martinvilu 
Esto es solo para que vean como funciona la cosa ;-)
:dagger:

**Comment by TomasSautu** [comment]
No quiero hacer esto, se lo podemos asignar a otro? @JeanFranco99 por ejemplo

**Comment by TomasSautu** [comment]
No me siento bien señorito Stark, quiero irme a casa 😢

**Comment by JeanFranco99** [comment]
Te juro por Dieguito Maradona que yo no fui, yo estaba en electricidad y lo vi a Galo entrar a reactor

**Comment by OrellanaGalo** [comment]
Quien hizo admin al profe? deberiamos sacarselo.

**Comment by OrellanaGalo** [comment]
> 
> 
> Te juro por Dieguito Maradona que yo no fui, yo estaba en electricidad y lo vi a Galo entrar a reactor

No, yo te vi salir de la ventilacion.

**Comment by GastonPrat** [comment]
________________
     |'-.--._ _________:
     |  /    |  __    __\
     | |  _  | [\_\= [\_\
     | |.' '. \.........|
     | ( <)  ||:       :|_
      \ '._.' | :.....: |_(o
       '-\_   \ .------./
       _   \   ||.---.||  _
      / \  '-._|/\n~~\n' | \
     (| []=.--[===[()]===[) |
     <\_/  \_______/ _.' /_/
     ///            (_/_/
     |\\            [\\
     ||:|           | I|
     |::|           | I|
     ||:|           | I|
     ||:|           : \:
     |\:|            \I|
     :/\:            ([])
     ([])             [|
      ||              |\_
     _/_\_            [ -'-.__
snd <]   \>            \_____.>
      \__/

**Comment by JeanFranco99** [comment]
Yo diria que votemos a @martinvilu tiene actitud sospechosa

**Comment by TomasSautu** [comment]
funado @martinvilu

**Comment by martinvilu** [comment]
Usar el issue tracker para jugar al One of Us, no es una mala idea...
